### ISSUE TITLE
Sintáxis/Código

### ISSUE THREAD

**Issue by lucasjaviluna** [AlessandroPaolini7/TP-TTADS#1]
[Low]
	- Hay muchos console.log
	- Hay una mezcla de español - inglés en los nombres de las variables y métodos. Lo usual es escribir todo en inglés. Ej:
	https://vscode.dev/github/AlessandroPaolini7/TP-TTADS/blob/main/tp-frontend/nospeak-project/nospeak_client/src/pages/Song/Song.jsx#L149
	- Hay hooks declarados pero que finalmente no se usan. Ej: https://vscode.dev/github/AlessandroPaolini7/TP-TTADS/blob/main/tp-frontend/nospeak-project/nospeak_client/src/App.js#L31
	- Si es algo que no cambia, es mejor usar const https://vscode.dev/github/AlessandroPaolini7/TP-TTADS/blob/main/tp-frontend/nospeak-project/nospeak_client/src/pages/Search/Search.jsx#L12
	- Quedó apuntando a localhost https://vscode.dev/github/AlessandroPaolini7/TP-TTADS/blob/main/tp-frontend/nospeak-project/nospeak_client/src/pages/MyLibrary/Library.jsx#L130
	- Este HOC no se está usando https://vscode.dev/github/AlessandroPaolini7/TP-TTADS/blob/main/tp-frontend/nospeak-project/nospeak_client/src/components/PrivateRoute.jsx#L4

**Comment by BautistaGuerra** [comment]
Todo lo otro ya está modificado
