### ISSUE TITLE
User Experience

### ISSUE THREAD

**Issue by lucasjaviluna** [AlessandroPaolini7/TP-TTADS#2]
[Middle]
	- En varias pantallas, no se muestra un loading o spinner para que el usuario se de cuenta de que algo está sucediendo. Ej: login, registro de usuario, etc

**Comment by BautistaGuerra** [comment]
- En login se muestra una alerta en la esquina inferior en verde que dice: "Successful login. Redirecting..."
- En register se muestra arriba del botón un campo que dice: "Registration successful! Logging In..."
- En las demás páginas como Artist, Playlist, Album, Account se muestra un mensaje que dice "Loading information..." o "Loading user information" hasta que se devuelven los datos de la API.
