### ISSUE TITLE
Redux

### ISSUE THREAD

**Issue by lucasjaviluna** [AlessandroPaolini7/TP-TTADS#3]
[Middle]
	- No está del todo bien tener en el reducer, lógica adicional no relacionada directamente con el cambio del state. Ej: limpiar el localStorage
	https://vscode.dev/github/AlessandroPaolini7/TP-TTADS/blob/main/tp-frontend/nospeak-project/nospeak_client/src/redux/slices/userSlice.js#L19
	Podrían ver otra forma de implementación o de solución a este tipo de casos, teniendo en cuenta los side effects https://redux.js.org/usage/side-effects-approaches
	o bien limpiar el storage antes de despachar la action logout

**Comment by BautistaGuerra** [comment]
Limpiamos el storage antes de despachar la acción de logout
